spring:
 datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    testWhileIdle: true
    validationQuery: SELECT 1
 jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
 mail:
   host: email-smtp.us-east-1.amazonaws.com
   port: 465
   protocol: smtps
   username: ${PUPI_MAIL_USERNAME}
   password: ${PUPI_MAIL_PASSWORD}
   properties.mail.smtp:
                    auth: true
                    starttls.enable: true

server:
  port: 5000