spring:
 datasource:
    url: jdbc:mysql://localhost:3306/pupi?useSSL=false
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
 jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
 mail:
   host: email-smtp.us-east-1.amazonaws.com
   port: 465
   protocol: smtps
   properties.mail.smtp:
                    auth: true
                    starttls.enable: true

server:
  port: 8080

java:
  runtime:
      version: 1.8