spring:
 datasource:
    url: 'jdbc:mysql://130.211.214.126:3306/pupi?useSSL=false'
    username: 'user'
    password: 'user'
    testWhileIdle: true
    validationQuery: SELECT 1
 jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
