spring:
 datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    testWhileIdle: true
    validationQuery: SELECT 1
 jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
 mail:
   host: email-smtp.us-east-1.amazonaws.com
   port: 465
   protocol: smtps
   properties.mail.smtp:
                    auth: true
                    starttls.enable: true

server:
  port: 5000

java:
  runtime:
      version: 1.8

app:
  aws:
      s3:
        bucketName: pupi-images
        accessKey: AKIAJMZIXQFQHRZGDRCQ
        secretKey: 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
      ses:
        accessKey: AKIAJC5QINGQL2PXT7TA
        secretKey: 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
